# Generated by Django 3.1.1 on 2020-10-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TaskChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_title', models.CharField(default='No changes.', max_length=305)),
                ('changed_description', models.TextField(default='No changes.')),
                ('changed_status', models.CharField(choices=[('new', 'NEW'), ('planned', 'PLANNED'), ('in progress', 'IN PROGRESS'), ('done', 'DONE')], default='No changes.', max_length=27)),
                ('changed_completion', models.CharField(default='No changes.', max_length=55)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
